[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[functions.getLetters]
  name = "getLetters"
  included_files = ["netlify/functions/getLetters.js"]
  external_node_modules = ["airtable"]

[functions.updateReaction]
  name = "updateReaction"
  included_files = ["netlify/functions/updateReaction.js"]
  external_node_modules = ["airtable"]

[functions.LetterApproved]
  node_bundler = "esbuild"

[build.environment]
  AIRTABLE_TOKEN = ""

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/ltg-wall"
  to = "/ltg-wall/index.html"
  status = 200
