[build]
  functions = "netlify/functions"
  publish = "public" # ← ensures Netlify serves HTML/CSS/JS from /public

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions."updateReaction"]
  external_node_modules = ["airtable"]

[functions."LetterApproved"]
  node_bundler = "esbuild"

[build.environment]
  AIRTABLE_TOKEN = ""

[[redirects]]
  from = "/ltg-wall"
  to = "/ltg-wall/index.html"
  status = 200
