[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[functions.get-letters]
  included_files = ["netlify/functions/get-letters.js"]
  external_node_modules = ["airtable"]

[functions.update-reaction]
  included_files = ["netlify/functions/update-reaction.js"]
  external_node_modules = ["airtable"]

[functions.LetterApproved]
  node_bundler = "esbuild"

[build.environment]
  AIRTABLE_TOKEN = ""

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/ltg-wall"
  to = "/ltg-wall/index.html"
  status = 200