[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/.netlify/functions/airtableRead"
  to = "/.netlify/functions/airtableRead"
  status = 200

[[redirects]]
  from = "/.netlify/functions/updateReaction"
  to = "/.netlify/functions/updateReaction"
  status = 200

[[redirects]]
  from = "/.netlify/functions/LetterApproved"
  to = "/.netlify/functions/LetterApproved"
  status = 200
